apiVersion: apps/v1 
kind: Deployment
metadata:
  name: app
  namespace: prod
  labels: 
     app: tasky

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: tasky

  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: 748033149816.dkr.ecr.us-east-2.amazonaws.com/prod/app:c84101747a19e401b28f0f152a8f9713ee477f9f
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1