apiVersion: apps/v1 
kind: Deployment
metadata:
  name: kubernetes-demo-tasky-app
  labels: 
     app: tasky

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: tasky

  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: 748033149816.dkr.ecr.us-east-2.amazonaws.com/prod/app:d490ad0bc828fe1d5208ef5822eb4d31c59e21cd
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1