apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-tasky-service
  labels:
    app: tasky 
spec:
  selector:
    app: tasky

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer